Repository MiniTeam6/MiniProject_BE, pull requests merged in 2023-05, with the labels that each got.

#1 Entity설계
  .gradle/7.6.1/checksums/checksums.lock
  .gradle/7.6.1/checksums/md5-checksums.bin
  .gradle/7.6.1/checksums/sha1-checksums.bin
  .gradle/7.6.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.6.1/dependencies-accessors/gc.properties
  .gradle/7.6.1/executionHistory/executionHistory.lock
  .gradle/7.6.1/fileChanges/last-build.bin
  .gradle/7.6.1/fileHashes/fileHashes.lock
  .gradle/7.6.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/jpa-buddy.xml
  .idea/misc.xml
  .idea/vcs.xml
  src/main/java/shop/mtcoding/restend/controller/AdminController.java
  src/main/java/shop/mtcoding/restend/core/config/MySecurityConfig.java
  src/main/java/shop/mtcoding/restend/model/Annual/Annual.java
  src/main/java/shop/mtcoding/restend/model/Duty/Duty.java
  src/main/java/shop/mtcoding/restend/model/Event/Event.java
  src/main/java/shop/mtcoding/restend/model/Event/EventType.java
  src/main/java/shop/mtcoding/restend/model/Order/Order.java
  src/main/java/shop/mtcoding/restend/model/Order/OrderState.java
  src/main/java/shop/mtcoding/restend/model/transaction/temp
  src/main/java/shop/mtcoding/restend/model/user/User.java
Labels: feature

#13 feat: 연차 당직 리스팅 무한스크롤 페이지네이션 (슬라이스), 파라미터 필터링, 내연차리스트, 내당직리스트
  src/main/java/shop/mtcoding/restend/controller/EventController.java
  src/main/java/shop/mtcoding/restend/controller/UserController.java
  src/main/java/shop/mtcoding/restend/model/event/EventRepository.java
  src/main/java/shop/mtcoding/restend/service/EventService.java
  src/main/java/shop/mtcoding/restend/service/UserService.java
Labels: feature

#20 Feat/test2 테스트 거의 완료!
  src/docs/asciidoc/api-docs.adoc
  src/main/java/shop/mtcoding/restend/controller/AdminController.java
  src/main/java/shop/mtcoding/restend/controller/EventController.java
  src/main/java/shop/mtcoding/restend/controller/UserController.java
  src/main/java/shop/mtcoding/restend/core/config/MyFilterRegisterConfig.java
  src/main/java/shop/mtcoding/restend/core/dummy/DataInit.java
  src/main/java/shop/mtcoding/restend/core/dummy/DummyEntity.java
  src/main/java/shop/mtcoding/restend/dto/event/EventRequest.java
  src/main/java/shop/mtcoding/restend/dto/user/UserRequest.java
  src/main/java/shop/mtcoding/restend/model/annual/Annual.java
  src/main/java/shop/mtcoding/restend/model/event/Event.java
  src/main/resources/db/teardown.sql
  src/test/java/shop/mtcoding/restend/controller/EventControllerTest.java
  src/test/java/shop/mtcoding/restend/controller/UserControllerTest.java
  src/test/java/shop/mtcoding/restend/controller/UserControllerUnitTest.java
  src/test/java/shop/mtcoding/restend/model/user/UserRepositoryTest.java
  src/test/java/shop/mtcoding/restend/service/UserServiceTest.java
Labels: test

#42 API 테스트 중간 확인(수정, 모든 이벤트 남음)
  src/docs/asciidoc/Event-API.adoc
  src/test/java/shop/mtcoding/restend/controller/EventControllerTest.java
Labels: documentation

#70 회원리스트 정렬 오름차순으로 변경&에러코드추가&어드민 테스트코드
  .github/workflows/main.yml
  Dockerfile_spring2
  build.gradle
  build/classes/java/main/shop/mtcoding/restend/dto/event/EventRequest$EventCancelInDto.class
  build/classes/java/main/shop/mtcoding/restend/dto/event/EventRequest$EventModifyInDto.class
  build/classes/java/main/shop/mtcoding/restend/dto/user/UserResponse$UserDetailOutDTO.class
  build/classes/java/main/shop/mtcoding/restend/dto/user/UserResponse$UserListOutDTO.class
  build/classes/java/main/shop/mtcoding/restend/model/user/User.class
  build/classes/java/main/shop/mtcoding/restend/service/EventService.class
  build/classes/java/main/shop/mtcoding/restend/service/UserService.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/docs/asciidoc/Event-API.adoc
  src/docs/asciidoc/Member-API.adoc
  src/docs/asciidoc/code.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/shop/mtcoding/restend/core/advice/MyExceptionAdvice.java
  src/main/java/shop/mtcoding/restend/core/advice/MyValidAdvice.java
  src/main/java/shop/mtcoding/restend/core/dummy/DataInit.java
  src/main/java/shop/mtcoding/restend/core/exception/Exception400.java
  src/main/java/shop/mtcoding/restend/core/exception/Exception401.java
  src/main/java/shop/mtcoding/restend/core/exception/Exception403.java
  src/main/java/shop/mtcoding/restend/core/exception/Exception404.java
  src/main/java/shop/mtcoding/restend/core/exception/Exception500.java
  src/main/java/shop/mtcoding/restend/core/util/MyFileUtil.java
  src/main/java/shop/mtcoding/restend/core/util/MyFilterResponseUtil.java
  src/main/java/shop/mtcoding/restend/dto/ResponseDTO.java
  src/main/java/shop/mtcoding/restend/dto/order/OrderResponse.java
  src/main/java/shop/mtcoding/restend/dto/user/UserResponse.java
  src/main/java/shop/mtcoding/restend/model/event/EventRepository.java
  src/main/java/shop/mtcoding/restend/model/event/EventType.java
  src/main/java/shop/mtcoding/restend/model/order/Order.java
  src/main/java/shop/mtcoding/restend/model/order/OrderState.java
  src/main/java/shop/mtcoding/restend/model/user/User.java
  src/main/java/shop/mtcoding/restend/model/user/UserRole.java
  src/main/java/shop/mtcoding/restend/service/EventService.java
  src/main/java/shop/mtcoding/restend/service/OrderService.java
  src/main/java/shop/mtcoding/restend/service/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/image.jpg
  src/test/java/shop/mtcoding/restend/controller/AdminControllerTest.java
  src/test/java/shop/mtcoding/restend/controller/AdminControllerTest2.java
  src/test/java/shop/mtcoding/restend/controller/EventControllerTest.java
  src/test/java/shop/mtcoding/restend/controller/UserControllerTest.java
  src/test/java/shop/mtcoding/restend/core/MyRestDoc.java
  src/test/java/shop/mtcoding/restend/core/RestDocument.java
  src/test/java/shop/mtcoding/restend/core/RestDocumentApi.java
Labels: feature

#71 도커허브에 푸시하는 과정 추가
  .github/workflows/main.yml
  Dockerfile_spring2
  build.gradle
  src/main/java/shop/mtcoding/restend/RestendApplication.java
  src/main/java/shop/mtcoding/restend/controller/UserController.java
  src/main/java/shop/mtcoding/restend/core/dummy/DataInit.java
  src/main/java/shop/mtcoding/restend/core/dummy/DummyEntity.java
  src/main/java/shop/mtcoding/restend/model/duty/DutyRepository.java
  src/main/java/shop/mtcoding/restend/model/event/EventRepository.java
  src/main/java/shop/mtcoding/restend/model/log/ErrorLog.java
  src/main/java/shop/mtcoding/restend/model/log/ErrorLogRepository.java
  src/main/java/shop/mtcoding/restend/model/log/LoginLog.java
  src/main/java/shop/mtcoding/restend/model/log/LoginLogRepository.java
  src/main/java/shop/mtcoding/restend/model/order/OrderRepository.java
  src/main/java/shop/mtcoding/restend/model/user/UserRepository.java
  src/main/java/shop/mtcoding/restend/service/AnnualService.java
  src/main/java/shop/mtcoding/restend/service/EventService.java
  src/main/java/shop/mtcoding/restend/service/OrderService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/db/teardown.sql
  src/test/java/shop/mtcoding/restend/controller/EventControllerTest.java
Labels: enhancement
